AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Buckets Infrastructure'

Resources:
  S3Orders:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: lks-orders-adelyaf01-2026
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ArchiveAndExpire
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: INTELLIGENT_TIERING
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedOrigins:
              - "*"
      Tags:
        - Key: Name
          Value: lks-orders-adelyaf01-2026

  S3Logs:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: lks-logs-adelyaf01-2026
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LifecycleConfiguration:
        Rules:
          - Id: LogsLifecycle
            Status: Enabled
            Transitions:
              - TransitionInDays: 7
                StorageClass: INTELLIGENT_TIERING
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: lks-logs-adelyaf01-2026

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Orders
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${S3Orders}/*

Outputs:
  S3OrdersBucketName:
    Value: !Ref S3Orders
    Export:
      Name: LKS-S3Orders-Name
  S3LogsBucketName:
    Value: !Ref S3Logs
    Export:
      Name: LKS-S3Logs-Name